[project]
name = "josuke"
version = "0.0.1"
dependencies = ["click", "click-spinner", "eth-abi", "eth-utils", "eth-hash[pycryptodome]", "requests"]

[project.optional-dependencies]
test = ["pytest", "pytest-timeout"]

[project.scripts]
josuke = "josuke.cli:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
